# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt5.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 645)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.selectFolderBtn = QtWidgets.QPushButton(self.centralwidget)
        self.selectFolderBtn.setGeometry(QtCore.QRect(110, 30, 113, 32))
        self.selectFolderBtn.setObjectName("selectFolderBtn")
        self.convertBtn = QtWidgets.QPushButton(self.centralwidget)
        self.convertBtn.setGeometry(QtCore.QRect(420, 30, 113, 32))
        self.convertBtn.setObjectName("convertBtn")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(40, 130, 291, 461))
        self.listWidget.setObjectName("listWidget")
        self.undoListView = QtWidgets.QListView(self.centralwidget)
        self.undoListView.setGeometry(QtCore.QRect(40, 131, 291, 461))
        self.undoListView.setObjectName("undoListView")
        self.listWidget_2 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_2.setGeometry(QtCore.QRect(400, 131, 361, 461))
        self.listWidget_2.setObjectName("listWidget_2")
        self.doneListView = QtWidgets.QListView(self.centralwidget)
        self.doneListView.setGeometry(QtCore.QRect(400, 130, 361, 461))
        self.doneListView.setObjectName("doneListView")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton.setGeometry(QtCore.QRect(350, 280, 31, 41))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.binaryLayeredBtn = QtWidgets.QPushButton(self.centralwidget)
        self.binaryLayeredBtn.setGeometry(QtCore.QRect(560, 30, 151, 32))
        self.binaryLayeredBtn.setObjectName("binaryLayeredBtn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 60, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(400, 10, 60, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(540, 40, 21, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(140, 100, 60, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(550, 100, 71, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 60, 761, 16))
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.selectFolderBtn.setText(_translate("MainWindow", "目录扫描"))
        self.convertBtn.setText(_translate("MainWindow", "直接转换"))
        self.commandLinkButton.setText(_translate("MainWindow", "CommandLinkButton"))
        self.binaryLayeredBtn.setText(_translate("MainWindow", "动静脉期分层转换"))
        self.label.setText(_translate("MainWindow", "第一步骤"))
        self.label_2.setText(_translate("MainWindow", "第二步骤"))
        self.label_3.setText(_translate("MainWindow", "OR"))
        self.label_4.setText(_translate("MainWindow", "待做列表"))
        self.label_5.setText(_translate("MainWindow", "已完成列表"))
        self.label_6.setText(_translate("MainWindow", "-----------------------------------------------------------------------------------------------------------------------------"))
